// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	// General System Links
	NotificationType_NOTIFICATION_TYPE_SYSTEM_LEETCODE_LINKED   NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_SYSTEM_MONKEYTYPE_LINKED NotificationType = 2
	// LeetCode Verification Flow
	NotificationType_NOTIFICATION_TYPE_LEETCODE_VERIFICATION_STARTED   NotificationType = 9
	NotificationType_NOTIFICATION_TYPE_LEETCODE_VERIFICATION_SUCCEEDED NotificationType = 10
	NotificationType_NOTIFICATION_TYPE_LEETCODE_VERIFICATION_FAILED    NotificationType = 11
	// Monkeytype Verification Flow
	NotificationType_NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_STARTED   NotificationType = 12
	NotificationType_NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_SUCCEEDED NotificationType = 13
	NotificationType_NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_FAILED    NotificationType = 14
	// Social
	NotificationType_NOTIFICATION_TYPE_SOCIAL_FOLLOW   NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_SOCIAL_COMMENT  NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_SOCIAL_MENTION  NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_SOCIAL_REPLY    NotificationType = 6
	NotificationType_NOTIFICATION_TYPE_SOCIAL_REACTION NotificationType = 7
	// Gaming/Progress
	NotificationType_NOTIFICATION_TYPE_ACHIEVEMENT_UNLOCKED NotificationType = 8
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0:  "NOTIFICATION_TYPE_UNSPECIFIED",
		1:  "NOTIFICATION_TYPE_SYSTEM_LEETCODE_LINKED",
		2:  "NOTIFICATION_TYPE_SYSTEM_MONKEYTYPE_LINKED",
		9:  "NOTIFICATION_TYPE_LEETCODE_VERIFICATION_STARTED",
		10: "NOTIFICATION_TYPE_LEETCODE_VERIFICATION_SUCCEEDED",
		11: "NOTIFICATION_TYPE_LEETCODE_VERIFICATION_FAILED",
		12: "NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_STARTED",
		13: "NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_SUCCEEDED",
		14: "NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_FAILED",
		3:  "NOTIFICATION_TYPE_SOCIAL_FOLLOW",
		4:  "NOTIFICATION_TYPE_SOCIAL_COMMENT",
		5:  "NOTIFICATION_TYPE_SOCIAL_MENTION",
		6:  "NOTIFICATION_TYPE_SOCIAL_REPLY",
		7:  "NOTIFICATION_TYPE_SOCIAL_REACTION",
		8:  "NOTIFICATION_TYPE_ACHIEVEMENT_UNLOCKED",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":                       0,
		"NOTIFICATION_TYPE_SYSTEM_LEETCODE_LINKED":            1,
		"NOTIFICATION_TYPE_SYSTEM_MONKEYTYPE_LINKED":          2,
		"NOTIFICATION_TYPE_LEETCODE_VERIFICATION_STARTED":     9,
		"NOTIFICATION_TYPE_LEETCODE_VERIFICATION_SUCCEEDED":   10,
		"NOTIFICATION_TYPE_LEETCODE_VERIFICATION_FAILED":      11,
		"NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_STARTED":   12,
		"NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_SUCCEEDED": 13,
		"NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_FAILED":    14,
		"NOTIFICATION_TYPE_SOCIAL_FOLLOW":                     3,
		"NOTIFICATION_TYPE_SOCIAL_COMMENT":                    4,
		"NOTIFICATION_TYPE_SOCIAL_MENTION":                    5,
		"NOTIFICATION_TYPE_SOCIAL_REPLY":                      6,
		"NOTIFICATION_TYPE_SOCIAL_REACTION":                   7,
		"NOTIFICATION_TYPE_ACHIEVEMENT_UNLOCKED":              8,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notification_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_PRIORITY_LOW    Priority = 0
	Priority_PRIORITY_MEDIUM Priority = 1
	Priority_PRIORITY_HIGH   Priority = 2
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_LOW",
		1: "PRIORITY_MEDIUM",
		2: "PRIORITY_HIGH",
	}
	Priority_value = map[string]int32{
		"PRIORITY_LOW":    0,
		"PRIORITY_MEDIUM": 1,
		"PRIORITY_HIGH":   2,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_notification_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_notification_notification_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Type          NotificationType       `protobuf:"varint,4,opt,name=type,proto3,enum=metacode.notification.v1.NotificationType" json:"type,omitempty"`
	Priority      Priority               `protobuf:"varint,5,opt,name=priority,proto3,enum=metacode.notification.v1.Priority" json:"priority,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SendRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *SendRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_LOW
}

func (x *SendRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SendRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Delivered      bool                   `protobuf:"varint,2,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

var File_notification_notification_proto protoreflect.FileDescriptor

const file_notification_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fnotification/notification.proto\x12\x18metacode.notification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x03\n" +
	"\vSendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12>\n" +
	"\x04type\x18\x04 \x01(\x0e2*.metacode.notification.v1.NotificationTypeR\x04type\x12>\n" +
	"\bpriority\x18\x05 \x01(\x0e2\".metacode.notification.v1.PriorityR\bpriority\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12O\n" +
	"\bmetadata\x18\a \x03(\v23.metacode.notification.v1.SendRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\fSendResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x1c\n" +
	"\tdelivered\x18\x02 \x01(\bR\tdelivered*\xc1\x05\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12,\n" +
	"(NOTIFICATION_TYPE_SYSTEM_LEETCODE_LINKED\x10\x01\x12.\n" +
	"*NOTIFICATION_TYPE_SYSTEM_MONKEYTYPE_LINKED\x10\x02\x123\n" +
	"/NOTIFICATION_TYPE_LEETCODE_VERIFICATION_STARTED\x10\t\x125\n" +
	"1NOTIFICATION_TYPE_LEETCODE_VERIFICATION_SUCCEEDED\x10\n" +
	"\x122\n" +
	".NOTIFICATION_TYPE_LEETCODE_VERIFICATION_FAILED\x10\v\x125\n" +
	"1NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_STARTED\x10\f\x127\n" +
	"3NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_SUCCEEDED\x10\r\x124\n" +
	"0NOTIFICATION_TYPE_MONKEYTYPE_VERIFICATION_FAILED\x10\x0e\x12#\n" +
	"\x1fNOTIFICATION_TYPE_SOCIAL_FOLLOW\x10\x03\x12$\n" +
	" NOTIFICATION_TYPE_SOCIAL_COMMENT\x10\x04\x12$\n" +
	" NOTIFICATION_TYPE_SOCIAL_MENTION\x10\x05\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_SOCIAL_REPLY\x10\x06\x12%\n" +
	"!NOTIFICATION_TYPE_SOCIAL_REACTION\x10\a\x12*\n" +
	"&NOTIFICATION_TYPE_ACHIEVEMENT_UNLOCKED\x10\b*D\n" +
	"\bPriority\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x00\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x01\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x022l\n" +
	"\x13NotificationService\x12U\n" +
	"\x04Send\x12%.metacode.notification.v1.SendRequest\x1a&.metacode.notification.v1.SendResponseB=Z;github.com/metacode-dream-team/MetaCode/pkg/pb/notificationb\x06proto3"

var (
	file_notification_notification_proto_rawDescOnce sync.Once
	file_notification_notification_proto_rawDescData []byte
)

func file_notification_notification_proto_rawDescGZIP() []byte {
	file_notification_notification_proto_rawDescOnce.Do(func() {
		file_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)))
	})
	return file_notification_notification_proto_rawDescData
}

var file_notification_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notification_notification_proto_goTypes = []any{
	(NotificationType)(0),         // 0: metacode.notification.v1.NotificationType
	(Priority)(0),                 // 1: metacode.notification.v1.Priority
	(*SendRequest)(nil),           // 2: metacode.notification.v1.SendRequest
	(*SendResponse)(nil),          // 3: metacode.notification.v1.SendResponse
	nil,                           // 4: metacode.notification.v1.SendRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_notification_notification_proto_depIdxs = []int32{
	0, // 0: metacode.notification.v1.SendRequest.type:type_name -> metacode.notification.v1.NotificationType
	1, // 1: metacode.notification.v1.SendRequest.priority:type_name -> metacode.notification.v1.Priority
	5, // 2: metacode.notification.v1.SendRequest.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: metacode.notification.v1.SendRequest.metadata:type_name -> metacode.notification.v1.SendRequest.MetadataEntry
	2, // 4: metacode.notification.v1.NotificationService.Send:input_type -> metacode.notification.v1.SendRequest
	3, // 5: metacode.notification.v1.NotificationService.Send:output_type -> metacode.notification.v1.SendResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_notification_notification_proto_init() }
func file_notification_notification_proto_init() {
	if File_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_proto_rawDesc), len(file_notification_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_proto_goTypes,
		DependencyIndexes: file_notification_notification_proto_depIdxs,
		EnumInfos:         file_notification_notification_proto_enumTypes,
		MessageInfos:      file_notification_notification_proto_msgTypes,
	}.Build()
	File_notification_notification_proto = out.File
	file_notification_notification_proto_goTypes = nil
	file_notification_notification_proto_depIdxs = nil
}
