version: '3.8'

services:

  gateway:
    image: sayansayan123/metacode-gateway:latest
    container_name: metacode-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config/api-gateway-docker.yaml:/root/config/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - metacode

  auth-service:
    image: sayansayan123/metacode-auth-service:latest
    container_name: metacode-auth-service
    env_file: .env
    environment:
      - ENVIRONMENT=dev.docker
      - PORT=8080
      - HOST=localhost
      - LOGLEVEL=${LOGLEVEL}
      - FRONTEND_URL=${FRONTEND_URL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - EMAIL_FROM=${EMAIL_FROM}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
    networks:
      - metacode

  integration-service:
    image: sayansayan123/metacode-integration-service:latest
    container_name: metacode-integration-service
    env_file: .env
    environment:
      - ENVIRONMENT=dev.docker
      - PORT=8080
      - LOGLEVEL=${LOGLEVEL}
      - REDIS_ADDR=${REDIS_ADDR}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPIC=${INTEGRATION_TOPIC}
      - KAFKA_GROUP_ID=${INTEGRATION_GROUP}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${INTEGRATION_MONGO_DB_NAME}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_APP_REDIRECT_URI=${GITHUB_APP_REDIRECT_URI}
      - APE_KEY=${APE_KEY}
      - NOTIFICATION_SERVICE_GRPC_URL=notification-service:50055
    networks:
      - metacode

  activity-gamification-service:
    image: sayansayan123/metacode-activity-gamification-service:latest
    container_name: metacode-activity-gamification-service
    env_file: .env
    environment:
      - ENVIRONMENT=dev.docker
      - PORT=8080
      - LOGLEVEL=${LOGLEVEL}
      - REDIS_ADDR=${REDIS_ADDR}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPICS=${GAMIFICATION_TOPICS}
      - KAFKA_PRODUCER_TOPIC=${GAMIFICATION_TOPIC}
      - NOTIFICATION_SERVICE_GRPC_URL=metacode-notification-service:50055
      - KAFKA_GROUP_ID=${GAMIFICATION_GROUP}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${GAMIFICATION_MONGO_DB_NAME}
    networks:
      - metacode

  user-profile-service:
    image: sayansayan123/metacode-user-profile-service:latest
    container_name: metacode-user-profile-service
    env_file: .env
    environment:
      - ENVIRONMENT=dev.docker
      - PORT=8080
      - LOGLEVEL=${LOGLEVEL}
      - REDIS_ADDR=${REDIS_ADDR}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPICS=${USER_TOPICS}
      - KAFKA_GROUP_ID=${USER_GROUP}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${USER_MONGO_DB_NAME}
    networks:
      - metacode

  file-service:
    image: sayansayan123/metacode-file-service:latest
    container_name: metacode-file-service
    env_file: .env
    environment:
      - ENVIRONMENT=dev.docker
      - PORT=8080
      - LOGLEVEL=${LOGLEVEL}
      - REDIS_ADDR=${REDIS_ADDR}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPIC=${FILE_TOPIC}
      - KAFKA_GROUP_ID=${FILE_GROUP}
      - POSTGRES_DSN=${FILE_POSTGRES_DSN}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_PUBLIC_HOST=${MINIO_PUBLIC_HOST}
    networks:
      - metacode

  notification-service:
    image: sayansayan123/metacode-notification-service:latest
    container_name: metacode-notification-service
    env_file: .env
    environment:
      - ENVIRONMENT=dev.docker
      - PORT=8080
      - GRPC_PORT=50055
      - LOGLEVEL=${LOGLEVEL}
      - REDIS_ADDR=${REDIS_ADDR}
      - POSTGRES_DSN=${NOTIFICATION_POSTGRES_DSN}
    networks:
      - metacode

  engagement-service:
    image: sayansayan123/metacode-engagement-service
    container_name: metacode-engagement-service
    env_file: .env
    environment:
      - ENVIRONMENT=dev.docker
      - PORT=8080
      - POSTGRES_DSN=${ENGAGEMENT_POSTGRES_DSN}
      - MONGO_DB=${ENGAGEMENT_MONGO_DB}
      - MONGO_DB_NAME=${ENGAGEMENT_MONGO_DB_NAME}
      - KAFKA_BROKERS=${ENGAGEMENT_KAFKA_BROKERS}
      - KAFKA_GROUP_ID=${ENGAGEMENT_KAFKA_GROUP_ID}
      - KAFKA_TOPICS=${ENGAGEMENT_KAFKA_TOPICS}
      - KAFKA_PRODUCER_TOPIC=${ENGAGEMENT_KAFKA_PRODUCER_TOPIC}
    networks:
        - metacode

networks:
  metacode:
    driver: bridge