port: "8080"
redis_addr: "redis:6379" # if redis is containerized, otherwise keep external

keycloak_url: "http://metacode.tailba5377.ts.net:8080/auth"
keycloak_realm: "metacode"

allowed_issuers:
  - "http://metacode.tailba5377.ts.net:8080/auth/realms/metacode"

services:
  - name: auth-service
    prefix: /v1/auth
    target: http://metacode-auth-service:8080
    public: true

  - name: integration-service
    prefix: /v1/integration
    target: http://metacode-integration-service:8080
    auth_required: true

  - name: activity-gamification-service
    prefix: /v1/activity
    target: http://metacode-activity-gamification-service:8080
    auth_required: true

  - name: engagement-service
    prefix: /v1/engagement
    target: http://metacode-engagement-service:8080
    auth_required: true

  - name: file-service
    prefix: /v1/fileservice
    target: http://metacode-file-service-service:8080
    auth_required: true

  - name: user-profile-service
    prefix: /v1/profiles
    target: http://metacode-user-profile-service:8080
    auth_required: true

  - name: notification-service
    prefix: /v1/notification
    target: http://metacode-notification-service:8080
    auth_required: true

    rules:
      - pattern: /admin
        email_verified: true

      - pattern: /public
        auth: false