name: Deploy Docker Compose to Server

on:
  push:
    branches:
      - main

jobs:
  deploy-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy docker-compose remotely
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/user

            curl -H "Authorization: token $DEPLOY_PAT" \
                 -H "Accept: application/vnd.github.v3.raw" \
                 -L \
                 https://api.github.com/repos/metacode-dream-team/metacode/contents/docker-compose-remote.yaml?ref=main \
                 -o docker-compose.yaml

            docker compose up -d
          EOF
        env:
          DEPLOY_PAT: ${{ secrets.DEPLOY_PAT }}