name: Deploy Docker Compose to Server

on:
  push:
    branches:
      - main

jobs:
  deploy-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          ssh-passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}

      - name: Deploy docker-compose remotely
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/user

            curl -H "Authorization: token $DEPLOY_PAT" -L \
            https://raw.githubusercontent.com/metacode-dream-team/metacode/main/docker-compose-remote.yaml \
            -o docker-compose.yaml

            docker compose up -d
          EOF
        env:
          DEPLOY_PAT: ${{ secrets.DEPLOY_PAT }}