name: Deploy Docker Compose to Server

on:
  push:
    branches:
      - main

jobs:
  deploy-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy docker-compose.yaml to server
        run: |
          scp -i ${{ secrets.SERVER_SSH_KEY }} -P 22 ./docker-compose-remote.yaml \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/user/docker-compose.yaml

      - name: Start or restart containers
        run: |
          ssh -i ${{ secrets.SERVER_SSH_KEY }} -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          'cd /home/user && docker compose up -d'